/*
 * Class auto generated by TexturePacker
 * 
 * Contains references to each image within the sprite sheet.
 *
 * http://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:4db67160ace91a4e3b6ec6c04f087182:579b8153697e168c0c95bfac529c5ed1:9a64b4e81de2af0c8b824c4008874009$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class unsaved
	{
		public const string Wanderer = "Wanderer";
	}
}